const products = [
  "The Legend of Zelda: Breath of the Wild",
  "Super Mario Odyssey",
  "Animal Crossing: New Horizons",
  "Mario Kart 8 Deluxe",
  "Splatoon 2",
  "Super Smash Bros. Ultimate",
  "Pokémon Sword",
  "Pokémon Shield",
  "Luigi's Mansion 3",
  "Super Mario Maker 2",
  "Fire Emblem: Three Houses",
  "Xenoblade Chronicles 2",
  "Astral Chain",
  "Octopath Traveler",
  "Hyrule Warriors: Age of Calamity",
  "Ring Fit Adventure",
  "Paper Mario: The Origami King",
  "Mario Tennis Aces",
  "Mario Party Superstars",
  "Super Mario 3D World + Bowser's Fury",
  "New Pokémon Snap",
  "Monster Hunter Rise",
  "Legend of Zelda: Skyward Sword HD",
  "Bravely Default II",
  "Metroid Dread",
  "Bayonetta 3",
  "No More Heroes III",
  "Pikmin 3 Deluxe",
  "Daemon X Machina",
  "Monster Hunter Stories 2: Wings of Ruin",
  "Shin Megami Tensei V",
  "Splatoon 3",
  "Advance Wars 1+2: Re-Boot Camp",
  "The Elder Scrolls V: Skyrim",
  "Doom Eternal",
  "Overwatch",
  "Fortnite",
  "Minecraft",
  "Rocket League",
  "Apex Legends",
  "FIFA 22",
  "NBA 2K22",
  "Madden NFL 22",
  "Crash Bandicoot 4: It's About Time",
  "Spyro Reignited Trilogy",
  "Tony Hawk's Pro Skater 1 + 2",
  "Mortal Kombat 11",
  "Street Fighter V: Champion Edition",
  "Guilty Gear -Strive-",
  "Tekken 7",
  "Devil May Cry 5 Special Edition",
  "Resident Evil Village",
  "Final Fantasy VII Remake Intergrade",
  "Ratchet & Clank: Rift Apart",
  "Demon's Souls",
  "Returnal",
  "Gran Turismo 7",
  "Horizon Forbidden West",
  "God of War Ragnarok",
  "Spider-Man: Miles Morales",
  "Sackboy: A Big Adventure",
  "LittleBigPlanet 3",
  "Ghost of Tsushima",
  "Death Stranding Director's Cut",
  "The Last of Us Part II",
  "Ghostwire: Tokyo",
  "Kena: Bridge of Spirits",
  "Hogwarts Legacy",
  "Far Cry 6",
  "Assassin's Creed Valhalla",
  "Cyberpunk 2077",
  "Watch Dogs: Legion",
  "Hitman 3",
  "Resident Evil 7: Biohazard",
  "Yakuza: Like a Dragon",
  "Scarlet Nexus",
  "Tales of Arise",
  "Nier Replicant ver.1.22474487139...",
  "Persona 5 Strikers",
  "Lost Judgment",
  "Bravely Default II",
  "Monster Hunter Rise",
  "Shin Megami Tensei III: Nocturne HD Remaster",
  "NEO: The World Ends with You",
  "Legend of Mana Remastered",
  "Final Fantasy XIV Online: Endwalker",
  "Scarlet Nexus",
  "Tales of Arise",
  "Nier Replicant ver.1.22474487139...",
  "Persona 5 Strikers",
  "Lost Judgment",
  "Hades",
  "Celeste",
  "Hollow Knight",
  "Dead Cells",
  "Ori and the Will of the Wisps",
  "Shovel Knight",
  "Stardew Valley",
  "Cuphead",
  "Undertale",
];

module.exports = products;
